#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1545773677                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :          https://support.plex.tv/articles/200264746-quick-start-step-by-step-guides/                                 # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Interlude                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stream music you own.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Uppalled Inc.
your_link                                 :                   
your_city                                 : 127.0.0.1                                
email_address                             : harjapuppal@gmail.com
github_username                           : uppalled



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Access to your Plex music library
    description                           : Your full library of music, from anywhere. Sign in to plex and just press play. 
    fontawesome_icon_name                 : chevron-right

  - title                                 : Listen Offline
    description                           : Smart caching helps save your data, and prevent unneeded stress on your Plex Media Server.
    fontawesome_icon_name                 : magic
    
  - title                                 : Dark Mode Support
    description                           : The lights are automagically synced with your phones settings.
    fontawesome_icon_name                 : adjust
    
  - title                                 : Airplay
    description                           : Audio your way, play it on your speakers, airpods, in your car, literally any device with a bluetooth connection.
    fontawesome_icon_name                 : volume-up
    
  - title                                 : All the general music player features
    description                           : Yup, all of them.
    fontawesome_icon_name                 : music
    
  - title                                 : An app designed around you
    description                           : Tabs like recently played and newly uploaded music so you can find exactly what you're in the mood for.
    fontawesome_icon_name                 : user

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#EC9C9E"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#EC9C9E"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#EC9C9E"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
